### ISSUE TITLE
Same Speed of scrolling

### ISSUE THREAD

**Issue by Sanath91009** [maxdietel/react-native-synced-scroll-views#2]
Hey , How to maintain same speed for all the scrollings ?
Thanks in advance

**Comment by maxdietel** [comment]
The ScrollViews are synced. Meaning they will reach the end and start of their content always at the same time. If you want to have 2, scrolling at the same speed they need to have the same relation of ScrollView size to Content size. If you have 2 ScrollViews with the same size but different content sizes they will not scroll with the same speed or one would reach the end while the other wouldn't. If you want to achieve a behaviour like that, you will need to modify the component yourself

**Comment by dhanaforu** [comment]
@MaximilianDietel03 Firstly, I would like to appreciate for your work on this cool library. Though SyncedScrollView works perfectly for my usecase, there is this small issue on speed/sync of offset between active and inactive scrollviews.

I have set both width and height same for the content across scrollviews. However, I see some lags in scrolling speed for active scroll view and other inactive scroll views. Kindly check the attached videos. You can see the issue more clearly on Android than iOS device. It would be really great if this issue has been fixed.

Thanks in advance.

https://user-images.githubusercontent.com/16042764/215493185-79d48876-da34-47f4-88d7-eab21a7b6c7e.mov


https://user-images.githubusercontent.com/16042764/215493134-408b311a-d123-44b9-894c-7e2584da903a.mp4

**Comment by maxdietel** [comment]
Hey @dhanaforu, I'm glad that you like the component. Maybe try to play around with the scrollEventThrottle. Making it smaller may reduce the offset but also needs more performance. I can't imagine something else than the scrollEventThrottle being the problem here. Set it to 1 and see what happens.
Notice tho: If setting scrollEventThrottle to 1 is resolving the issue, dont' use it. Some devices on the lower end might not be able to process this many updates and then this issue is sadly a limitation I can't fix

**Comment by dhanaforu** [comment]
@MaximilianDietel03 I have already tried with scrollEventThrottle, however nothing seems to be working.

**Comment by maxdietel** [comment]
@dhanaforu, as much as I would like to help you out and have a look at the code again myself, I don't have time for that at the moment. For now, it probably makes sense to merge the Scrollviews into one. After all, the issue you are addressing only appears in a context where you can also just merge the two conflicting Synced Scrollviews into one. Have a look at the video above again. You could just use one not synced Scrollview for the same result.

**Comment by dhanaforu** [comment]
@MaximilianDietel03 I could have used one scrollview if I don't have section header(i.e. cyan row) where it gets collapsed/expanded upon tapping it. Anyways thank you for your rapid response and suggestions. I will await for your fix for this.

**Comment by maxdietel** [comment]
@dhanaforu, this is easy to go around. Just use one synced ScrollView for every header instead of for every column and then just generate the columns inside of the synced ScrollView. Also, this would make much more sense from a structuring perspective. Pls feel free to correct me if I am getting this wrong.
